#cloud-config
# source: https://gist.github.com/syntaqx/9dd3ff11fb3d48b032c84f3e31af9163
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCRlzngviWKkc1aw0Ra5FUZ+hbIWDKq0Dq/50HiyFhThS7n3FW7D+YI58PoUovEqDL3cKneqKYGKytOwYU5cZUzhMd2ZVY9m/ppvIXY4apSftWGcmSCcl6fSkOzsSp2kIkmTyZPUuFgpVnOLAQLxRRPd26Gk+NskfRQGA5jDtbRbZxpOufFD9xiv3Xf8gkjz7Ua9caUBi4QP3Y/f76lDzbDKMYNdvdyXSuYFSFwSZplIfRApqO8lrcdkNezUmGSYLTVITH6XPr/wMoIF/PAL1+3pmmOgESUbcCeT1Z/dJ6I5mC1Rqb6c3twCRrT5i8/bpiKehsWYWTCiYEu30b2g8ir aws-key
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [docker]
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
final_message: "The system is finally up, after $UPTIME seconds"
write_files:
  - path: /home/ubuntu/dockerfile
    content: |
      FROM php:8.0-apache
      WORKDIR /var/www/html/
      COPY src .
      EXPOSE 80
      RUN ["docker-php-ext-install", "mysqli"]
  - path: /home/ubuntu/docker-compose.yml
    content: |
      version: "3.8"
      name: kn04-compose-b
      services:
        database:
          image: mariadb:latest
          container_name: m347-kn04a-db
          ports:
            - "3306:3306"
          environment:
            - MARIADB_ROOT_PASSWORD=example
          networks:
            - kn04-network

        web:
          image: m347-kn04a-web:latest
          container_name: m347-kn04a-web-b
          ports:
            - "80:80"
          depends_on:
            - database
          networks:
            - kn04-network

      networks:
        kn04-network:
          driver: bridge
          ipam:
            config:
              - subnet: 172.20.0.0/16
                ip_range: 172.20.5.0/24
                gateway: 172.20.5.254
  - path: /home/ubuntu/src/db.php
    content: |
      <?php
      //database
      $servername = "m347-kn04a-db";
      $username = "root";
      $password = "example";

      // Create connection
      $conn = new mysqli($servername, $username, $password);
      // Check connections
      if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
      }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
        echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      ?>
  - path: /home/ubuntu/src/info.php
    content: |
      <?php
        phpinfo();
      ?>
runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - cd /home/ubuntu
  - sudo docker build -t m347-kn04a-web /home/ubuntu -f /home/ubuntu/dockerfile
  - sudo docker compose up -d