# Verwendet das offizielle PHP-Image mit Apache als Basis
FROM php:8.0-apache
 
ENV DB_HOST=localhost:3306
ENV DB_USER=db_user
ENV DB_PASSWORD=db_password
ENV DB_NAME=mydatabase
 
# Kopiert die PHP-Dateien in den entsprechenden Ordner
COPY info.php /var/www/html/info.php
COPY db.php /var/www/html/db.php
# Installiert das PHP mysqli-Modul
RUN docker-php-ext-install mysqli
 
# Call db.php during the build process to configure it#
RUN php -f /var/www/html/db.php > /var/www/html/db_output.html
 
EXPOSE 80