version: "3.8"
name: kn04-compose
services:
  database:
    image: mariadb:latest
    container_name: m347-kn04a-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=example
    networks:
      - kn04-network
  web:
    image: m347-kn04a-web:latest
    container_name: m347-kn04a-web2
    ports:
      - "5600:80"
    depends_on:
      - database
    networks:
      - kn04-network
networks:
  kn04-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254
