# specifies the image
FROM nginx 

# Set working directory to nginx web root
WORKDIR /usr/share/nginx/html

# Copy index.html from current directory to nginx web root
COPY index.html .

# will listen on port 80 at runtime
EXPOSE 80
